controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /connexion
    controller: App\Controller\UserController::login

app_logout:
    path: /deconnexion
    controller: App\Controller\UserController::logout

